# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1f78eb30b74ee666d2ef761556949f39539f645b45a1056c9d4de3de458aef4731b600b7363cd7fb70507143c7ac0ac74158b14e71f0a692f1ebb36f7bd9f78

test:
  secret_key_base: 82f7817ecc5f007d54f2e569c00b554a81df5ed928744a79eba5b80b27e613dd5d2dff0d6f90bf5212f46429dd4d7df4671562cf4edffa3359146e9cfb52fd33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
